server:
  port: 8764

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  routes:
    zuul:
      path: /consumer/**
      service-id: consume



